"""added inference_time

Revision ID: 70142068f85c
Revises: 572587f16bbf
Create Date: 2026-04-01 15:46:46.429994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70142068f85c'
down_revision = '572587f16bbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('inference_time', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('result', 'inference_time')
    # ### end Alembic commands ###
